### ISSUE TITLE
Nonsense (idk what to name this)

### ISSUE THREAD

**Issue by JasonP01** [xpdustry/imperium#10]
We need you to add command descriptions to the discord commands, these are very confusing, also `/player info` is very revealing when what we currently get doesnt give info to doxx players

Secondly, which file/where is the anti afk code, i wanna look at it but am too lazy to search every file (took quick gander and needs depth search)

**Comment by phinner** [comment]
> We need you to add command descriptions to the discord commands
Still haven't implemented that. I did added English translations for Mindustry commands today tho.

> these are very confusing, also /player info is very revealing when what we currently get doesnt give info to doxx players
I already fixed it, it will only show sensitive info to those who have perms to see them.

> Secondly, which file/where is the anti afk code
Haven't implemented that yet I'm afraid.
