### ISSUE TITLE
GIve me collaborator

### ISSUE THREAD

**Issue by JasonP01** [xpdustry/imperium#118]
### What you are suggesting

I believe that it is in *my* best interest that you give me collaborator on this repository so i can make changes that obviously do not need revision, to be smart ill obviously commit through prs, so whatever i do is easily revertible on github itself, this suggestion comes from the annoyance of you not accepting template prs or text updates that do not cause issues with the rest of the plugin or presumably whatever you have in your local clone. Thank you.

**Comment by phinner** [comment]
Huh, no. As for the text part, I already have a solution for that, but I need some time.
