### ISSUE TITLE
Admin setblock command

### ISSUE THREAD

**Issue by JasonP01** [xpdustry/imperium#129]
### What you are suggesting

Setblock command so an admin can spawn in blocks, whether it be for fixing a grief (eg: someone griefed sources or a core) or just for "shenanigans" (who doesnt want a core in the middle of nowhere?)

**Comment by JasonP01** [comment]
I plan on attempting to make this myself, as my own personal challenge, i need/want to learn more!

**Comment by JasonP01** [comment]
@phinner after looking at what you did, i no longer care to do it myself as its so much nonsense... i will be fine with you just using what you wrote

I will request cmd name be changed to `setblock` as its just better ~~dont need to type a dash~~

**Comment by phinner** [comment]
Merged in master
