### ISSUE TITLE
Hard restrict commands

### ISSUE THREAD

**Issue by phinner** [xpdustry/imperium#13]
Some commands such as `killall` should not be available in game-modes other than sandbox.
Current idea for the implementation would be a server command that hide them, a little like MoreCommands do. Users with the admin rank should still be able to access these commands.

**Comment by JasonP01** [comment]
Currently cn doesnt even tell the user the commands (unlike fish) so you cant even find them, and ofcourse server returns unknown command for no access 

i know this as foos client can use tab to autocomplete commands and stuff, it also suggests commands based on what you typed, such as you can find /ipban on fish as a regular user using foos while it doesnt appear in /help 

(These are probably unhelpful waste, should i stop with these random comments? Idk how well you know how cn does things, without looking at the code ofc)

**Comment by phinner** [comment]
> Currently cn doesnt even tell the user the commands (unlike fish) so you cant even find them, and ofcourse server returns unknown command for no access

It's still the case, I just haven't put gamemode based filters on these commands yet.

> i know this as foos client can use tab to autocomplete commands and stuff, it also suggests commands based on what you typed, such as you can find /ipban on fish as a regular user using foos while it doesnt appear in /help

:skull: You scared me for a second, I checked [the source](https://github.com/mindustry-antigrief/mindustry-client/blob/fe03fb35534097f94c5edb5640e744d9c8f1be97/core/src/mindustry/client/utils/CommandCompletion.java#L16) and it only works if you have the foos plugin on your server, which isn't our case.

> (These are probably unhelpful waste, should i stop with these random comments? Idk how well you know how cn does things, without looking at the code ofc)

Mate, these are very helpful. Helpful comments and issues are always welcome.

**Comment by JasonP01** [comment]
Lol didnt mean to scare you, fish still has rank based commands its just how i found how to find it (they have /ipban but no /ban its weird), also on the foos plugin i talked to buthed about it (not for here lol, i was just curious) and seems to be useful to have that doesnt provide extra stuff besides proper client communication (almost all of the current staff, atleast the active ones) use foos client

**Comment by phinner** [comment]
Implemented in https://github.com/xpdustry/imperium/commit/5aabf27b5b9282f087660c6c69a910d0dabfa5c3
