### ISSUE TITLE
Mindustry auto responder

### ISSUE THREAD

**Issue by JasonP01** [xpdustry/imperium#141]
### What you are suggesting

Simply because people have the inate ability to not report griefers, whenever someone in chat says "someone griefed", "who griefed", "why did you delete" and the like it prompts them with a chat notif (everyone can see) to /report or /rt the grief for a moderator to handle it

Obv cooldown of like 5 min as to not spam it

**Comment by phinner** [comment]
Meh, I'd rather not rely on the content of a random message for this kind of thing.
The "report" tip is enough for now.
