### ISSUE TITLE
Name filter

### ISSUE THREAD

**Issue by JasonP01** [xpdustry/imperium#151]
### What you are suggesting

Filter that prevent players from joining with a certain name, better to be configurable so mods/admins can actively update the list of bypasses

**Comment by phinner** [comment]
🤔 Mmmh, we do have name filtering but it only covers cracked clients https://github.com/xpdustry/imperium/blob/master/imperium-mindustry/src/main/kotlin/com/xpdustry/imperium/mindustry/security/CrackedClientGatekeeper.kt

It would indeed be nice to also block slurs and other funny words.

**Comment by JasonP01** [comment]
> 🤔 Mmmh, we do have name filtering but it only covers cracked clients

E

Time for another project i can do :) (this is easier than figuring out /ban in cmd format)

**Comment by phinner** [comment]
So yeah, the real problem was finding a efficient algorithm for it, but I did find one so it's cool. The bad word list solution is viable thanks to it. See https://github.com/xpdustry/bad-words.
