### ISSUE TITLE
Identity evading detection

### ISSUE THREAD

**Issue by JasonP01** [xpdustry/imperium#16]
If u havent done/planned this already 

If a user changes name/device send a message to all staff ingame saying the player has changed identites from x -> y (like how foos does with autotrace)

Useful for staff to know if a player attempted to change their device/name to "hide" their identity after griefing or something 

Some reasons to not send it is if the previous name matched atleast 60% of the original (so you dont notify for slight name changes, like colour) or
Events where the user has marked 2 uuids as linked (nice for mobile/pc switching not notify for that uuid change, if the name is 60% matching ofc)

Second clause as i would not want staff notified of my joining on my mobile/pc as i use them interchangeably, also on this note to not notify if someone logged into a staff account changed names, some people do this to go undercover and catch griefers 

Oh and a ingame tip thats more common than not to remind people to /login to an account if they have one, or /register to make one to get perks/rewards (people have skillissue remembering this)

**Comment by buthed010203** [comment]
> Some reasons to not send it is if the previous name matched atleast 60% of the original (so you dont notify for slight name changes, like colour)

Or just Strings.stripColors()

**Comment by JasonP01** [comment]
> Or just Strings.stripColors()

I just gave colours as an example, if someone changes 1 character there is no point in notifying us

**Comment by phinner** [comment]
So, if I understand correctly, you want to be notified when a player leaves and rejoins with another name or uuid ?

**Comment by JasonP01** [comment]
> So, if I understand correctly, you want to be notified when a player leaves and rejoins with another name or uuid ?

yes, whatever foos does with its autotrace would be nice if the server did it for us, since we dont get normal trace info (entirely just asking for foos autotrace shenanigans to be provided)

**Comment by phinner** [comment]
![image](https://github.com/xpdustry/imperium/assets/62483793/f0ac70ea-ba9a-4c7f-8851-31926867dac5)
Implemented in https://github.com/xpdustry/imperium/commit/84765ce440747edc4921e4c3194fc5614e0def06
