### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by JasonP01** [xpdustry/imperium#169]
### What you are suggesting

Cant even get punishment ID ingame, while its cool to have ingame its also useless

/ban and the rest are cool, until you realize its useless to vanilla users, as everything ingame is snowflakes not the playerID (foos gives playerID in tab list)

also not very obvious it wants the playerID vanilla provides, as the server and everything else also calls the snowflake playerID 

as well as required reason for the / cmds when its coded to have an outcome without a reason, its still required

**Comment by JasonP01** [comment]
shouldve been bugs but whatever

**Comment by phinner** [comment]
In game ban commands accept online players (supports entity id, partial name and uuid for now).
The description of these commands need to be fixed.
