### ISSUE TITLE
Tilelogs

### ISSUE THREAD

**Issue by JasonP01** [xpdustry/imperium#17]
Ive noticed that there really isnt tilelogs, there is /history but thats so intuitive to use and slow as u have to enter 4 different arguements per tile to check if someone griefed `/history tile x y` 

It would be alot better to keep the double tab tilelogs as its so much better and faster for us, even non staff use tilelogs in that way for reporting and checking griefing 

May be a hassle to implement, as iirc log did something funky with storing player actions? May be unrelated

**Comment by phinner** [comment]
There is `/history interactive` that mimics the double tap feature.

**Comment by JasonP01** [comment]
Its not good to need a command to activate it when we are quickly trying to moderate someone (if they leave we have to go to discord to yeet them which is annoying)

**Comment by JasonP01** [comment]
Its alot easier for us to have it constantly on, people rarely ever doubleclick (for false positive of not wanting it) and even then it was a /pref for us to toggle it, in the end it would be in our best interest on being fast ~~and lazy~~ to just have it like it currently is on cn

**Comment by JasonP01** [comment]
> that mimics the double tap feature. 

More bad as single clicking be spamming our chat >:( and i dont have time to figure out how to spell interactive every time i need to check tilelogs

**Comment by phinner** [comment]
Implemented in https://github.com/xpdustry/imperium/commit/524a0cc5788472360a05a62974eac11e9a037135
