### ISSUE TITLE
Flags

### ISSUE THREAD

**Issue by JasonP01** [xpdustry/imperium#170]
### Where did the bug happen?

Mindustry

### The bug(s)

when flags are used as command arguements, when you dont use the flag and instead try entering the requirements in order (like the list in /help) while it says it accepts flag and regular order it throws syntax error.

Cmd: /command var var var/--var var/--var
/command 1 2 4 5 - syntax error
/command 1 2 --var 4 --var 5 - no syntax error
while 1st is supposed to be valid, it isnt

### Steps to reproduce it

try do /spawn ingame without entering the --flags, yet still fulfilling the arguements

### Submission

- [X] I have searched the open and closed issues to make sure this problem has not already been reported

**Comment by phinner** [comment]
Flags are named arguments, not positional arguments.
I don't see an easy way to fix it given how hacky their implementation is in [cloud](https://github.com/Incendo/cloud).

**Comment by JasonP01** [comment]
@phinner okay, would it be possible to atleast add a thing in distributor to not list flags as valid positional arguements, as it is confusing. Thx
