### ISSUE TITLE
Give admins the ability to restart servers and server auto restarts

### ISSUE THREAD

**Issue by JasonP01** [xpdustry/imperium#22]
Its well known that admins had the ability to restart the servers for reasons, bring this back as people (mainly staff) would tell admins to restart a server in cases of bugs with maps (such as too laggy to join the server)

On the same note, adding auto restart to the servers if they were to OOM or crash for any reason would also be nice, so the serverd couldnt go down.  - upon communication with zeta, more of a thing to make sure it always hosts itself forever, unless manually turned off

 As for the map on in the above instance,  it would make an autosave named `restart.msav` and load that specific save when it restarted (obviously for crashes it wouldnt save the map, so maybe it made on every 5min?)

**Comment by phinner** [comment]
> Its well known that admins had the ability to restart the servers for reasons, bring this back as people (mainly staff) would tell admins to restart a server in cases of bugs with maps (such as too laggy to join the server)

This would be tricky to implement because in the new system, servers are only aware of each other when they are up, I may implement something like that in the future.

> As for the map on in the above instance, it would make an autosave named restart.msav and load that specific save when it restarted (obviously for crashes it wouldnt save the map, so maybe it made on every 5min?)

Implemented a few hours ago.

**Comment by JasonP01** [comment]
> This would be tricky to implement because in the new system, servers are only aware of each other when they are up, I may implement something like that in the future.

I was more refrencing the discord part rather that being able to restart servers from ingame, it doesnt have to be fancy it could literally just be:

`/restart server:survival | attack | pvp` and it just calls the restart function that the consoles use :p, this can also be events where for some magical reasons servers died and *dont* restart on their own

**Comment by JasonP01** [comment]
Being able to easily just restart an offline/misbehaving server while you and zeta are asleep will always be more useful than not
