### ISSUE TITLE
Fix `none` option in map list filter

### ISSUE THREAD

**Issue by JasonP01** [xpdustry/imperium#236]
### Where did the bug happen?

Discord

### The bug(s)

When selectinf `none` it displays all maps regardless of gamemodes they have, instead of just the maps with no gamemodes set

### Steps to reproduce it

Run `/map list` with the gamemode argument of `none`

### Submission

- [X] I have searched the open and closed issues to make sure this problem has not already been reported

**Comment by phinner** [comment]
Fixed
