### ISSUE TITLE
Invalidated identity

### ISSUE THREAD

**Issue by JasonP01** [xpdustry/imperium#25]
Server said im sussy on mobile when game ended, did this twice.
Nothing was changed, no special nonsense my end.

What features are stripped when invalid? Im also still logged into staff when it says this.
(this is a bug)
![Screenshot_20231204_110002_Mindustry](https://github.com/xpdustry/imperium/assets/131086642/12cf1cc8-0962-4cbc-8268-a7855e6db5ca)

**Comment by phinner** [comment]
It's a security feature from distributor for permissions.
I simply forgot to reset them when I moved the servers (since the usid is bound per ip + **port**).
I will reset it when most servers will be migrated and ready.

**Comment by phinner** [comment]
Oh wait, I need to keep this open to not forget

**Comment by JasonP01** [comment]
lol, luckily there is basically 0 things involved for that anyway (afaik)
