### ISSUE TITLE
Tilelogs are using generated playerID when it should be using the new id system

### ISSUE THREAD

**Issue by JasonP01** [xpdustry/imperium#267]
### Where did the bug happen?

Mindustry

### The bug(s)

During the migration you didnt make tilelogs use the new ID system, the current ban commands dont accept the generated playerID and therefore it is unhelpful during moderation 

Happened on 1/10/24 from `.semperor`
![screenshot_1473](https://github.com/user-attachments/assets/7efaa5b6-5d79-4a84-8192-49921053cbf4)

Current:
![Screenshot_20241010_134356_Mindustry](https://github.com/user-attachments/assets/e92e9c4a-8044-4ba4-9744-2dcc81c15ace)

### Steps to reproduce it

Simply open tilelogs

### Submission

- [x] I have searched the open and closed issues to make sure this problem has not already been reported

**Comment by phinner** [comment]
![thanos-snap-emoji](https://github.com/user-attachments/assets/ce1e2a30-a1bf-408a-b3ed-d0fdda5c45a0)

**Comment by JasonP01** [comment]
I even pinged you for this the day semp sent that image....

**Comment by phinner** [comment]
Fixed
