### ISSUE TITLE
Map updating variable doesnt work

### ISSUE THREAD

**Issue by JasonP01** [xpdustry/imperium#283]
### Where did the bug happen?

Discord

### The bug(s)

When using the map updating variable the map doesnt even get added, /map search still shows the old map and it has not updated ingame either 

### Steps to reproduce it

Upload a map, upload a second map with a different name to update the first. Notice it doesnt want to update

### Submission

- [X] I have searched the open and closed issues to make sure this problem has not already been reported

**Comment by JasonP01** [comment]
I dont have a ss of it as i just deleted the old map as a workaround for updating it

**Comment by phinner** [comment]
Already fixed, the bot was likely not updated correctly, but it's fine now.

**Comment by JasonP01** [comment]
Likely
