### ISSUE TITLE
Nohorny qol

### ISSUE THREAD

**Issue by JasonP01** [xpdustry/imperium#316]
### What you are suggesting

When nohorny gives "suspected nsfw image" providing the name and identifier of the user who placed it would be nice

**Comment by phinner** [comment]
Already implemented, haven't pushed it yet :(
https://github.com/xpdustry/imperium/blob/4f106ff2843a4dfde446527a495d58256698ddd7/imperium-mindustry/src/main/kotlin/com/xpdustry/imperium/mindustry/security/LogicImageListener.kt#L72-L83
