### ISSUE TITLE
Notify players when a power void is destroyed

### ISSUE THREAD

**Issue by phinner** [xpdustry/imperium#32]
> **Suggestion from discord** 
[TheRedBlueCube2#4145] (30/10/2022 18:18)
make notifications that an enemy power void has been broken in chat (accepted but never added, currently only foos users
get that info)

**Comment by JasonP01** [comment]
https://github.com/mindustry-antigrief/mindustry-client/blob/648ba517fa472cca385093dc4e3eb392308e62c7/core/src/mindustry/client/ClientLogic.kt#L203

Foos void death code, i could probably pr this in somehow if you feel like not doing this anytime soon, ill ofc test it by compiling it ingame
