### ISSUE TITLE
Moderation Kick Length Bugs

### ISSUE THREAD

**Issue by JasonP01** [xpdustry/imperium#4]
When selecting a moderation reason ingame using the kick option, the select times menu is useless.

The kick times seem to be based on the reason given and not whatever the moderator chooses

Reason | Kick Length:

Moderator Kick | 1 hour
Griefing | 3 hours
Being Rude | 1 day
Griefing Core | 3 days
Griefing Defenses | 1 week
Griefing Power | moderation error #12
Other Reason | moderation error #12

No matter what time is selected by the moderator it does the above times

**Comment by phinner** [comment]
Okay, the new system no longer let the admins choose the duration. Its either a permanent ban or a temporary ban whom the duration is calculated automatically (number of previous bans times the "seriousness" of the offense).
I think this system will be easier for everyone involved.
I will close this issue but if you have suggestions for this new system or want to be able to set the duration for certain cases (you will have to give me examples for that), DM me on Discord.

**Comment by phinner** [comment]
Eh... I changed some things so I'll reopen so I will not forget

**Comment by phinner** [comment]
This should be solved now.
