### ISSUE TITLE
Send kick to ingame from discord

### ISSUE THREAD

**Issue by JasonP01** [xpdustry/imperium#41]
When a user is kicked from discord send the kick message ingame, this makes it easier for people to know that an action was done on a player. (Better than us going to live chats to say it)

When said player is kicked, make the server send the ban message to the last server that person was on (so it doesnt send to every server)

Something like the message that exists already for ingame kicking. 
( *player* was banned for *duration*
 Reason: *reason* )

**Comment by phinner** [comment]
> When a user is kicked from discord send the kick message ingame, this makes it easier for people to know that an action was done on a player. (Better than us going to live chats to say it)
>
> Something like the message that exists already for ingame kicking.
( player was banned for duration
Reason: reason )

Isn't it already the case ?

https://github.com/xpdustry/imperium/blob/096e97d353d4ee6d02489e984ee2c872eb0c2ab9/imperium-mindustry/src/main/kotlin/com/xpdustry/imperium/mindustry/security/PunishmentListener.kt#L75-L76

> When said player is kicked, make the server send the ban message to the last server that person was on (so it doesnt send to every server)

Players would be happy to know when a ban evader has been banned, will think about that. 🤔

**Comment by JasonP01** [comment]
Afaik it doesn't send a ban message ingame when kicked from the discord /ban command

**Comment by JasonP01** [comment]
I asked immor and he confirmed it did not send the kick to the servers :p

**Comment by phinner** [comment]
> I asked immor and he confirmed it did not send the kick to the servers :p

I tried in-game and it works.
Do more than asking next time
