### ISSUE TITLE
Password issue

### ISSUE THREAD

**Issue by JasonP01** [xpdustry/imperium#42]
Space characters are counted as valid characters in passwords, i believe it shouldnt be. Due to it being counted mobile autofill (from word suggestions) doesnt work nicely as it adds a space after the autofill, therefore making the server say the password is wrong

Usernames unaffected by spaces

**Comment by phinner** [comment]
> Space characters are counted as valid characters in passwords, i believe it shouldnt be. Due to it being counted mobile autofill (from word suggestions) doesnt work nicely as it adds a space after the autofill, therefore making the server say the password is wrong
> 
> Usernames unaffected by spaces

This is not a valid reason.
If your mobile keyboard does not like spaces, do not use them, or replace them by other special characters.
