### ISSUE TITLE
Trace langauge issue [bug]

### ISSUE THREAD

**Issue by JasonP01** [xpdustry/imperium#51]
When i trace someone it comes back as `langauge: en` no matter what even when the player is speaking russian/chinese, everyone is always displayed with `en` so im reporting this as bug

**Comment by JasonP01** [comment]
The chances of everyone ive ever traced being displayed as english and it being correct is unlikely

**Comment by phinner** [comment]
After investigation, turns out it's a bug in the game itself. I shall do a PR to fix it.
