### ISSUE TITLE
/mute ingame cmd

### ISSUE THREAD

**Issue by JasonP01** [xpdustry/imperium#56]
Very annoying going to discord (preferably works with the snowflake and/or uuid)

**Comment by phinner** [comment]
Bro did not read the latest changes, I already fixed it with the new admin action menu.

**Comment by JasonP01** [comment]
Bro did not know i cant exactly see the new menu rn and dont know what it have (its everything but whatev) 

I also have bigger skill issue with trying to compile imperium myself, i no no like docker :(
