### ISSUE TITLE
/core tp changes

### ISSUE THREAD

**Issue by JasonP01** [xpdustry/imperium#59]
First of all, it would be benifitial if it was just changed entirely to /wp, `/wp list` and /wp ~~tp~~ # less characters to type

For actual changes, it would be nice if instead of possessing the core, or respawning the player at the core, it just teleported the player to the core x,y. LIke how it did in logs version, plus support for flying units (and preferably nova tree since they *can* hover)

Reasoning:

1. This would allow bringing higher core tier units to lower core tier units, such as gamma -> shard core

2. It would *hopefully* be re-added to foos pathfinding, it had to be removed since it was made "bad"

3. Would make players happy :)

4. ~~would prevent me complaining about it~~

**Comment by phinner** [comment]
I will rework the /core commands to be simpler.
But the latter part about teleporting units, no.
Feels a little OP and we will have RTS controls in the next major update for unit management so yeah...

**Comment by JasonP01** [comment]
Logs command just set player xy to core center if unit.flying was true, it only worked if the unit was the player

And the part with foos, foos already can just pathfind there so its not a major thing, just qol
