### ISSUE TITLE
Move all server messages to bundles

### ISSUE THREAD

**Issue by JasonP01** [xpdustry/imperium#63]
Have every message server sends to clients be translated, to save api requests we can manually translate the common languages (ru, chinese, ukranian, spanish latin american, spanish, ect)

I am willing to do the translations and concur with actual users of that language for grammar and syntax

**Comment by JasonP01** [comment]
Later ill look into how to make the strings refer to bundle entries to add language support

**Comment by phinner** [comment]
Closing since its now a ongoing process.
