### ISSUE TITLE
Add telemetry and monitoring

### ISSUE THREAD

**Issue by phinner** [xpdustry/imperium#70]
Proper telemetry (and/or monitoring) for the different systems, such as: 
- maps (ratings)
- players (avg count, new, unique, retention)
- servers (TPS, RAM, GC, spark perhaps ?)

**Comment by Maxou-69** [comment]
also on map, we can add wave number. On player, number build blocks, number destroyed block, time of connection, time of connection per session.

**Comment by phinner** [comment]
Done
