### ISSUE TITLE
Allow Admins to restart servers from discord

### ISSUE THREAD

**Issue by JasonP01** [xpdustry/imperium#72]
Allows admins to restart the servers when an issue has arrised ingame, and/or
Allows admins to turn a server back on after it has crashed (such as OOM or another error) 
> would require some special edgecase where server pings a controller (such as the bot) that it is still alive every 5 minutes, and if it fails somehow let the bot turn the server back on

Log could do this easily as the machine was in physical access to him

**Comment by JasonP01** [comment]
This issue will likely be added to #70

**Comment by phinner** [comment]
Was implemented quite some time ago, forgot to close.
