### ISSUE TITLE
New votekick disconnect option

### ISSUE THREAD

**Issue by JasonP01** [xpdustry/imperium#74]
Currently, players can only do a votekick to remove players from the server, which is problematic when the point of the votekick is to remove someone annoying, but also its against the rules to kick someone for just being annoying.

So i propose, votekick button creates a menu choosing `disconnect / votekick` to either kick them for a period of time (regular votekick) or disconnect them, which would only remove them from the server like the vanilla admin disconnect button.

This allows players to remove an annoying person without facing the consequences of a false votekick, since the player could simple rejoin shortly after

*on a side note this would also sort of solve raids since most wont be able to handle a menu as a bot*

**Comment by Ayushkiller** [comment]
To fix raids just install the boteradicator by @theradioactivebanana

**Comment by TheRadioactiveBanana** [comment]
they have their own bot killer you cabbage

**Comment by Ayushkiller** [comment]
> they have their own bot killer you cabbage

Shut,I didnt knew.

**Comment by JasonP01** [comment]
lost my motivation for today, gonna attempt to start work on this, its honestly quite fun to make/look into this stuff, i learn more about kotlin and become better at coding. whether or not what i do will get accepted as is or at all :)

**Comment by JasonP01** [comment]
This solution would work but is likely not going to be implemented
