### ISSUE TITLE
Add filter for supicious link

### ISSUE THREAD

**Issue by Maxou-69** [xpdustry/imperium#75]
We need to protect our player in mindustry and our discord from phissing try. To do it what we can do:
In short term -> block **ALL** link send from discord
In long term -> setup a link verification with virustotal api or other

**Comment by TG-TG-TG-TG-TG-TG** [comment]
aww again France speed :p faster than me hah

**Comment by phinner** [comment]
Fixed by using a sane moderation bot.
Carl is cool but bloated... Sapphire is the future :sunglasses:.
