### ISSUE TITLE
Unit build capabilities 

### ISSUE THREAD

**Issue by JasonP01** [xpdustry/imperium#79]
Unit logic building is such an underutilised part of the game, and so far no servers in the entire community server list provide the ability to place it

I propose, using the account system, giving players who earned it the ability to place and config the ubuild instruction so we may now use it

To adress how to earn it:
> 1. Have it earned via active or hyperactive, something players can grind to get, it would provide a use back to those ranks (until /g is brought back)
> 
> 2. Have it staff assigned, so moderators can manually give players the ability to use ubuild, this option is safer as then griefers or trolls wouldnt be able to grind their way to automated griefing

To handle players who do not have the ability, simply reject their ability to place the ubuild instruction, log did this with imperium v2, and it showed a toast while still in the menu of the processor, and/or said it in chat to the user

It would require you to make a way to detect the logic configuration when a processor is configured, but would make us (CN) the only server in the entire community list, have some form of ubuild

**Comment by phinner** [comment]
https://github.com/xpdustry/imperium/commit/4187ab6977b32b9bca3b80bb9f14a6cc39ecb584
